name: Python DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Application
      run: python app.py

    - name: Run Build Script
      run: python build.py

    - name: Run Tests
      run: python test_app.py
